#!/usr/bin/env python3

import sys
import error
import parser
import paths

def main():
	try:
		sys.argv.index("-h")
	except ValueError:
		exit(start(sys.argv))
	else:
		exit(error.usage())

def start(argv):
	if (error.argError(argv)):
		return 84
	try:
		people, adjacency = parser.parser(argv[1])
	except TypeError:
		return 84
	# short = paths.compute_shortest_path_matrix(adjacency, 3)

	if (len(argv) == 4):
		short = paths.compute_shortest_path_matrix(adjacency, len(people))
		# if (argv[2] not in people or argv[3] not in people):
		# 	return 84
		print("Degree of separation between " + argv[2] + " and " + argv[3] + ": ", end='')
		try:
			print(short[people.index(argv[2])][people.index(argv[3])])
		except ValueError:
			print(-1)
	else:
		try:
			parser.peoples(people)
			print()
			parser.matrice(adjacency)
			print()
			short = paths.compute_shortest_path_matrix(adjacency, int(argv[2]))
			parser.matrice(short)
		except ValueError:
			error.usage()
			return 84

if __name__ == "__main__":
	main()